services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Synolia\SyliusMailTesterPlugin\:
        resource: '../../*'
        exclude: '../../{Controller,Fixture,SynoliaSyliusMailTesterPlugin.php}'

    Synolia\SyliusMailTesterPlugin\Controller\:
        resource: '../../Controller/*'
        tags: ['controller.service_arguments']

    Synolia\SyliusMailTesterPlugin\Fixture\ShopUserFixture:
        class: Synolia\SyliusMailTesterPlugin\Fixture\ShopUserFixture
        tags: ['sylius_fixtures.fixture']
        arguments:
            $exampleFactory: '@Synolia\SyliusMailTesterPlugin\Fixture\Factory\ShopUserExampleFactory'

    Synolia\SyliusMailTesterPlugin\Fixture\Factory\ShopUserExampleFactory:
        class: Synolia\SyliusMailTesterPlugin\Fixture\Factory\ShopUserExampleFactory

    Synolia\SyliusMailTesterPlugin\Menu\AdminMenuListener:
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }
