parameters:
    locale: en_US

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Synolia\SyliusMailTesterPlugin\:
        resource: '../../*'
        exclude: '../../{Fixture,SynoliaSyliusMailTesterPlugin.php}'

    Synolia\SyliusMailTesterPlugin\Fixture\ShopUserFixture:
        class: Synolia\SyliusMailTesterPlugin\Fixture\ShopUserFixture
        tags: ['sylius_fixtures.fixture']
        arguments:
            $exampleFactory: '@Synolia\SyliusMailTesterPlugin\Fixture\Factory\ShopUserExampleFactory'

    Synolia\SyliusMailTesterPlugin\Fixture\Factory\ShopUserExampleFactory:
        class: Synolia\SyliusMailTesterPlugin\Fixture\Factory\ShopUserExampleFactory

    # Temporary declare this service public to be used in test without use it yet in code
    Synolia\SyliusMailTesterPlugin\Resolver\FormTypeResolver:
        public: true
    Synolia\SyliusMailTesterPlugin\DataRetriever\EmailKeysDataRetriever:
        public: true
